version: '3.7'
services:
  web:
    build: .
    command: python /books/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/books
    ports:
      - 8000:8000
    depends_on:
      - db
    environment: # env variables
        - ENVIRONMENT = development
        - POSTGRES_NAME=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres

        - SECRET_KEY=8o*uo5_uv+6d7yd($$-d7p9)f=0gqf630+u79el@byead)&cxwu
        - DEBUG=1
        - STRIPE_TEST_PUBLISHABLE_KEY=<pk_test_your_publishable_key_here>
        - STRIPE_TEST_SECRET_KEY=<sk_test_your_secret_key_here> 

  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
        - POSTGRES_PASSWORD=postgres
volumes:
    postgres_data:
